version: 2.1

jobs:
  job1:
    docker:
      - image: cimg/base:2022.05  
    steps:
      - checkout
      - run:
         name: Dependency installation
         command: sudo apt-get update && sudo apt-get install -y python3-pip && pip3 install coverage
      - run:
         name: Run django test
         command: coverage run manage.py test

workflows:
    test_workflow:
        jobs:
            - job1