version: 2.1
orbs:
  python: circleci/python@2.0.3

jobs:
  job1:
    docker: 
        - image: python:3.7
    parallelism: 4
    steps:
      - checkout
      - run:
         name: Run test
         command: |
             pip install virtualenv
             virtualenv .venv
             source .venv/bin/activate
             cd test-circle
             mkdir test-reports
             pip install -r requirements.txt
             TESTFILES=$(circleci tests glob "**/tests/**/test*.py" "**/tests.py" | circleci tests split --split-by=timings)
             pytest --rootdir="." --junitxml=test-reports/python/junit.xml $TESTFILES
      - store_test_results:
          path: myapp/test-reports

workflows:
    test_workflow:
        jobs:
            - job1