version: 2.1
orbs:
  python: circleci/python@2.0.3

jobs:
  job1:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
         pkg-manager: pip
      - run:
         name: Run django test
         command: coverage run -m unittest discover
workflows:
    test_workflow:
        jobs:
            - job1