version: 2.1

jobs:
  job1:
    docker:
      - image: python/default  
    steps:
      - checkout
      - run:
         name: Run django test
         command: python -m unittest discover
workflows:
    test_workflow:
        jobs:
            - job1