version: 2.1

jobs:
  job1:
    docker:
      - image: cimg/base:2022.05  
    steps:
      - run:
         name: Echo output
         command: echo "job1 printing" 
     
  job2:
    docker:
      - image: cimg/base:2022.05  
    steps:
      - run: echo "Job to running!"
      
workflows:
    test_workflow:
        jobs:
            - job1
            - job2
