version: 2.1
orbs:
  python: circleci/python@2.0.3

jobs:
  job1:
    docker: 
        - image: python:3.7
    parallelism: 4
    steps:
      - checkout
      - run:
         name: Run test
         command: |
             pip install virtualenv
             virtualenv .venv
             source .venv/bin/activate
             pip install -r requirements.txt
             cp -f .circleci/resources/pytest_build_config.ini pytest.ini
             TESTFILES=$(circleci tests glob tests/**/tests.py | circleci tests split --split-by=timings)
             echo $TESTFILES
             mkdir -p test-results
             pytest **/tests.py
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
    test_workflow:
        jobs:
            - job1