version: 2.1
jobs:
  test:
    docker: 
        - image: python:3.7
    parallelism: 4
    steps:
      - checkout
      - run:
         name: Run test
         command: |
             pip install virtualenv
             virtualenv .venv
             source .venv/bin/activate
             mkdir test-reports
             pip install -r requirements.txt
             echo "$PWD"
             echo "print"
             echo "$(ls)"
             python manage.py test $(circleci tests glob "pages/tests.py" | circleci tests split)
             echo "$(ls)"
      - store_test_results:
          path: test-reports

workflows:
    version: 2
    test_workflow:
        jobs:
            - test