version: 2.1

jobs:
  job1:
    docker:
      - image: cimg/base:2022.05  
    steps:
      - checkout
      - run:
         name: Run django test
         command: python -m unittest discover

workflows:
    test_workflow:
        jobs:
            - job1