version: 2.1
orbs:
  python: circleci/python@2.0.3

jobs:
  job1:
    executor: python/default
    steps:
      - checkout
      - run:
         name: Run django test
         command: python -m unittest discover
workflows:
    test_workflow:
        jobs:
            - job1