version: 2.1
jobs:
  test:
    docker: 
        - image: python:3.7
    parallelism: 4
    steps:
      - checkout
      - run:
         name: Run test
         command: |
             pip install virtualenv
             virtualenv .venv
             source .venv/bin/activate
             mkdir test-reports
             pip install -r requirements.txt
             python -m pytest $(circleci tests glob "**/test_*.py" | circleci tests split)
      - store_test_results:
          path: test-reports

workflows:
    version: 2
    test_workflow:
        jobs:
            - test