version: 2.1
jobs:
  test:
    docker: 
        - image: python:3.7
    parallelism: 4
    steps:
      - checkout
      - run:
         name: Run test
         command: |
             pip install virtualenv
             virtualenv .venv
             source .venv/bin/activate
             mkdir test-reports
             pip install -r requirements.txt
             echo "$PWD"
             echo "$(ls)"
             TESTFILES=$(circleci tests glob "pages/tests.py")
             echo $TESTFILES | tr ' ' '\n' | sort | uniq > circleci_test_files.txt
             TESTFILES=$(circleci tests split --split-by=timings circleci_test_files.txt)
             TESTFILES=$(echo $TESTFILES | tr "/" "." | sed 's/.py//g')
             pytest $TESTFILES
      - store_test_results:
          path: test-reports

workflows:
    version: 2
    test_workflow:
        jobs:
            - test