version: 2.1
jobs:
  test:
    docker: 
        - image: python:3.7
    parallelism: 4
    steps:
      - checkout
      - run:
         name: Run test
         command: |
             pip install virtualenv
             virtualenv .venv
             source .venv/bin/activate
             mkdir test-reports
             pip install -r requirements.txt
             TESTFILES=$(circleci tests glob tests/**/test*.py | circleci tests split --split-by=timings)
             pytest $TESTFILES
      - store_test_results:
          path: test-reports

workflows:
    version: 2
    test_workflow:
        jobs:
            - test